---
- name: Get vector rpm
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    dest: "{{ ansible_user_dir }}/vector-{{ vector_version }}.rpm"
    mode: '0755'
  when: (ansible_facts.os_family == "RedHat")
- name: Install vector rpm
  become: true
  ansible.builtin.yum:
    name: "{{ ansible_user_dir }}/vector-{{ vector_version }}.rpm"
    state: installed
    disable_gpg_check: true
  when: ansible_facts.os_family == "RedHat"

- name: CONFIG | Set Vector config from template 1
  become: true
  ansible.builtin.template:
    src: vector.j2
    dest: /etc/vector/vector.yaml
    mode: '0755'

- name: Start vector process
  ansible.builtin.shell: vector --config /etc/vector/vector.yml >/dev/null 2>&1 &
  async: 10
  poll: 0
  changed_when: false