---
    # - name: Restart vector
    #   become: true
    #   ansible.builtin.service:
    #     name: vector
    #     state: restarted
    #     enabled: true
    #   listen: restart vector
  
    # - name: HANDLER | Reload vector
    #   become: true
    #   ansible.builtin.systemd_service:
    #     name: vector
    #     state: reloaded
    #   listen: reload vector